### ISSUE TITLE
Random "SOFT WDT reset" crashes

### ISSUE THREAD

**Issue by arushgupta2007** [esp8266/Arduino#6277]
#### Platform

- Hardware:					Nodemcu Amica ESP8266
- Core Version:			2.5.0
- Development Env:		Arduino IDE
- Operating System:		Windows

#### Settings in IDE

- Module:  			Nodemcu 1.0 (ESP-12E Module)
- Flash Size: 		4MB (no SPIFFS )
- lwip Variant:   v2 Lower Memory
- CPU Frequency:		80Mhz
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

I am using my Nodemcu to control the status of my bulb. For which I am using 2 triacs, ACS712 Current sensor and zero cross detection circuit. I am also using Firebase as my cloud service, so that I can see and change the status of my bulb using my phone. 
[link to firebase library I am using](https://github.com/mobizt/Firebase-ESP8266/)

I am experiencing random crashes after some time. It reads Soft WDT Reset 

### Sketch

```cpp

[code]
#include <ACS712.h>
#include <FirebaseESP8266.h>
#include <ESP8266WiFi.h>
#include <ArduinoJson.h>

#define FIREBASE_HOST "..."
#define FIREBASE_AUTH "..."
#define WIFI_SSID "..."
#define WIFI_PASSWORD "..."

ACS712 sensor(ACS712_05B, A0);
int delayto = 2000;
bool has_changed = false;
String path = "";
unsigned long previousMillis = 0;
const long interval = 1000;
int till = 0;
//int debug = 0;

FirebaseData firebaseData;
FirebaseData firebaseDatadiffrent_obj;
DynamicJsonBuffer json_buffer;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to Wi-Fi");
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(300);

  }
  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();

  pinMode(D2, INPUT);
  pinMode(D7, OUTPUT);
  pinMode(D8, OUTPUT);

  sensor.calibrate();

  attachInterrupt(digitalPinToInterrupt(D2), zcd, FALLING);

  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
  Firebase.reconnectWiFi(true);

  if (Firebase.getString(firebaseData, "/arushpass/device_path/esp{2615}")) {
    path = String("/arushpass" + firebaseData.stringData());
    Serial.println(path);
  }

  if (!Firebase.beginStream(firebaseData, path + "/controls"))
  {
    Serial.println("------------------------------------");
    Serial.println("Can't begin stream connection...");
    Serial.println("REASON: " + firebaseData.errorReason());
    Serial.println("------------------------------------");
    Serial.println();
  }
}

void loop() {
  if (millis() - previousMillis >= interval) {
    previousMillis = millis();
    while (Serial.available() > 0)
    {
      String bla = Serial.readString();
      float amps = bla.toFloat();
      Serial.println(amps);
      if (amps <= 0.04 && amps > 0.0) {
        Firebase.setBool(firebaseDatadiffrent_obj, String(path + "/status"), false);
      } else if (amps > 0.04) {
        till += 1;
        Firebase.setBool(firebaseDatadiffrent_obj, String(path + "/status"), true);
      }
    }
    if (!Firebase.readStream(firebaseData))
    {
            Serial.println("------------------------------------");
            Serial.println("Can't read stream data...");
            Serial.println("REASON: " + firebaseData.errorReason());
            Serial.println("------------------------------------");
            Serial.println();
    }

    if (firebaseData.streamTimeout())
    {
            Serial.println("Stream timeout, resume streaming...");
            Serial.println();
    }

    if (firebaseData.streamAvailable())
    {
            Serial.println("------------------------------------");
            Serial.println("Stream Data available...");
            Serial.println("STREAM PATH: " + firebaseData.streamPath());
            Serial.println("EVENT PATH: " + firebaseData.dataPath());
            Serial.println("DATA TYPE: " + firebaseData.dataType());
            Serial.println("EVENT TYPE: " + firebaseData.eventType());
            Serial.print("VALUE: ");
      if (firebaseData.dataType() == "int") {
        if (!firebaseData.dataPath().substring(1).equals("watts_used")) {
          detachInterrupt(digitalPinToInterrupt(D2));
          delayto = map(firebaseData.intData(), 1, 100, 9000, 2000);
          attachInterrupt(digitalPinToInterrupt(D2), zcd, FALLING);
        }
                Serial.println(firebaseData.intData());
      }
      else if (firebaseData.dataType() == "boolean") {
        has_changed = !has_changed;
                Serial.println(firebaseData.boolData() == 1 ? "true" : "false");
      }
            Serial.println("------------------------------------");
            Serial.println();
    }

  }
}

void zcd() {
  if (has_changed) {
    delayMicroseconds(delayto);
    digitalWrite(D8, HIGH);
    delayMicroseconds(50);
    digitalWrite(D8, LOW);
  } else {
    delayMicroseconds(delayto);
    digitalWrite(D7, HIGH);
    delayMicroseconds(50);
    digitalWrite(D7, LOW);
  }
}
[/code]
```

### Debug Messages

```


Decoding stack results:


0x4021230f: loop_task(ETSEvent*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_main.cpp line 133
0x40100349: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 166
0x40100278: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 130
0x4022ca4b: bi_int_multiply at crypto/bigint.c line 365
0x4022ca41: bi_int_multiply at crypto/bigint.c line 365
0x40100278: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 130
0x402318c4: SHA256_Update at crypto/sha256.c line 231
0x4022c916: bi_free at crypto/bigint.c line 219
0x4022c916: bi_free at crypto/bigint.c line 219
0x401001b4: delayMicroseconds at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring.c line 205
0x401001dd: __digitalWrite at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 82
0x40207382: zcd() at C:\Users\...\Documents\Arduino\esp_home_control/esp_home_control.ino line 143
0x40100349: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 166
0x40100338: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x40100349: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 166
0x40100278: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 130
0x4023190f: SHA256_Final at crypto/sha256.c line 257
0x4010033b: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x40100338: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x4010033b: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x40100338: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x4022ee56: SHA256_Process at crypto/sha256.c line 133
0x4023189d: SHA256_Update at crypto/sha256.c line 228
0x40100278: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 130
0x402314b6: SHA256_Process at crypto/sha256.c line 191
0x401001b4: delayMicroseconds at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring.c line 205
0x401001dd: __digitalWrite at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 82
0x40207382: zcd() at C:\Users\...\Documents\Arduino\esp_home_control/esp_home_control.ino line 143
0x40100349: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 166
0x40100338: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x40100278: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 130
0x4022f68e: SHA256_Process at crypto/sha256.c line 148
0x402318c4: SHA256_Update at crypto/sha256.c line 231
0x4021d981: glue2esp_linkoutput at glue-esp/lwip-esp.c line 299
0x4021dc03: new_linkoutput at glue-lwip/lwip-git.c line 233
0x4021dff4: ethernet_output at netif/ethernet.c line 312
0x402254ec: etharp_output_to_arp_index at core/ipv4/etharp.c line 770
0x402256f0: etharp_output_LWIP2 at core/ipv4/etharp.c line 885
0x40226108: ip4_output_if_opt_src at core/ipv4/ip4.c line 1007
0x40226150: ip4_output_if_opt at core/ipv4/ip4.c line 820
0x40226176: ip4_output_if at core/ipv4/ip4.c line 793
0x40226ce7: ip_chksum_pseudo at core/inet_chksum.c line 395
0x402230d6: tcp_output at core/tcp_out.c line 1361
0x4010014c: millis at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring.c line 183
0x40100c5c: free at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\umm_malloc\umm_malloc.c line 1760
0x40212354: esp_yield() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_main.cpp line 91
0x4020e177: ClientContext::_write_from_source(DataSource*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi\src/include/ClientContext.h line 466
0x4020e8bc: axTLS::__ax_port_write(int, uint8_t*, size_t) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi\src/include/ClientContext.h line 361
0x4022867c: send_packet at ssl/tls1.c line 1133
0x4020e858: axTLS::__ax_port_read(int, uint8_t*, size_t) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi\src\WiFiClientSecureAxTLS.cpp line 471
0x4022900b: basic_read at ssl/tls1.c line 1374
0x40228708: ssl_write at ssl/tls1.c line 355
0x40100278: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 130
0x4020eec3: axTLS::WiFiClientSecure::write(unsigned char const*, unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi\src/include/SSLContext.h line 382
0x402294e0: ssl_read at ssl/tls1.c line 314
0x40212354: esp_yield() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_main.cpp line 91
0x402118e1: Print::write(char const*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/Print.h line 60
0x4020ec18: axTLS::WiFiClientSecure::available() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi\src/include/SSLContext.h line 273
0x402118f4: Print::print(char const*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\Print.cpp line 122
0x4020d3be: FirebaseHTTPClient::http_sendHeader(char const*) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266HTTPClient.cpp line 58
0x4020d3ee: FirebaseHTTPClient::http_connect() at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266HTTPClient.cpp line 76
0x4020d449: FirebaseHTTPClient::http_sendRequest(char const*, char const*) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266HTTPClient.cpp line 65
0x40215819: __itoa at ../../../../../../dl/newlib-xtensa/newlib/libc/stdlib/itoa.c line 59
0x4010033b: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x402091f5: FirebaseESP8266::sendFirebaseRequest(FirebaseData&, char const*, unsigned char, unsigned char, char const*, char const*, unsigned int) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 3545
0x4020b1d6: FirebaseESP8266::firebaseConnect(FirebaseData&, std::string const&, unsigned char, unsigned char, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 1359
0x4022900b: basic_read at ssl/tls1.c line 1374
0x401001dd: __digitalWrite at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 82
0x40207382: zcd() at C:\Users\...\Documents\Arduino\esp_home_control/esp_home_control.ino line 143
0x40100349: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 166
0x40100338: interrupt_handler at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring_digital.c line 162
0x4020d7c4: ESP8266WiFiSTAClass::status() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp line 563
0x4020b878: FirebaseESP8266::firebaseConnect(FirebaseData&, std::string const&, unsigned char, unsigned char, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 1718
0x4020ce18: FirebaseESP8266::sendRequest(FirebaseData&, unsigned char, std::string const&, unsigned char, unsigned char, std::string const&, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 1828
0x4020d02a: FirebaseESP8266::buildRequest(FirebaseData&, unsigned char, unsigned char, std::string const&, char const*, bool, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 199
0x402118e1: Print::write(char const*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/Print.h line 60
0x4021cef0: operator new(unsigned int) at ../../../../../dl/gcc-xtensa/libstdc++-v3/libsupc++/new_op.cc line 52
0x4020d1ab: FirebaseESP8266::setBool(FirebaseData&, std::string const&, bool, bool, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 728
0x4021d7f2: std::basic_string  , std::allocator  >::basic_string(char const*, std::allocator  const&) at /workdir/arena/gcc/xtensa-lx106-elf/libstdc++-v3/include/bits/basic_string.tcc line 218
0x4010014c: millis at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_wiring.c line 183
0x4020d21b: FirebaseESP8266::setBool(FirebaseData&, String const&, bool) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 688
0x40211eb7: String::reserve(unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\WString.cpp line 146
0x40211f00: String::copy(char const*, unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\WString.cpp line 182
0x40211fec: String::operator=(String const&) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\WString.cpp line 220
0x40207795: loop() at C:\Users\...\Documents\Arduino\esp_home_control/esp_home_control.ino line 85
0x40212400: loop_wrapper() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266\core_esp8266_main.cpp line 125

```
Can anyone please help me out?

**Comment by devyte** [comment]
A whole lot of issues have been fixed since 2.5.0. I suggest trying 2.5.2 and/or latest git.
I don't see an issue at this time, so I'm closing. If you add info that points to a core issue, @ me and I'll reopen, or just open a new issue and fill in the required info.

**Comment by arushgupta2007** [comment]
@devyte  I am still having the problem using 2.5.2. 

###Stack Dump
```
0x4020e713: loop_task(ETSEvent*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_main.cpp line 133
0x4010020c: delayMicroseconds(unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring.cpp line 208
0x40100234: __digitalWrite(uint8_t, uint8_t) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 85
0x401000de: zcd() at C:\Users\...\Documents\Arduino\esp_home_control/esp_home_control.ino line 144
0x401003b1: interrupt_handler(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 169
0x401003a0: interrupt_handler(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 165
0x40100234: __digitalWrite(uint8_t, uint8_t) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 85
0x401002e0: interrupt_handler(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 133
0x40231fcf: SHA1ProcessMessageBlock at crypto/sha1.c line 169
0x402320b5: SHA1_Update at crypto/sha1.c line 81
0x402300e2: bi_subtract at crypto/bigint.c line 324
0x40210b2e: _umm_free(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\umm_malloc\umm_malloc.cpp line 1350
0x4022fd2a: bi_free at crypto/bigint.c line 219
0x4022fd2a: bi_free at crypto/bigint.c line 219
0x401003a3: interrupt_handler(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 165
0x401003a0: interrupt_handler(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 165
0x401002e0: interrupt_handler(void*) at C:\Users\..\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 133
0x40232a35: SHA256_Process at crypto/sha256.c line 97
0x40234cc0: SHA256_Update at crypto/sha256.c line 231
0x401003b1: interrupt_handler(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 169
0x401002e0: interrupt_handler(void*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 133
0x4022f32e: AES_cbc_encrypt at crypto/aes.c line 370
0x4022f29e: AES_cbc_encrypt at crypto/aes.c line 283
0x4020e758: esp_yield() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_main.cpp line 91
0x4020ece3: delay(unsigned long) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring.cpp line 54
0x4020812d: ClientContext::_write_from_source(DataSource*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi\src/include/ClientContext.h line 467
0x40208930: axTLS::__ax_port_write(int, uint8_t*, size_t) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi\src/include/ClientContext.h line 361
0x4022bae0: send_packet at ssl/tls1.c line 1133
0x402088c8: axTLS::__ax_port_read(int, uint8_t*, size_t) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi\src\WiFiClientSecureAxTLS.cpp line 472
0x4022c45b: basic_read at ssl/tls1.c line 1374
0x4022bb6c: ssl_write at ssl/tls1.c line 355
0x40208f43: axTLS::WiFiClientSecure::write(unsigned char const*, unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi\src/include/SSLContext.h line 382
0x4022c930: ssl_read at ssl/tls1.c line 314
0x4020da69: Print::write(char const*) at C:\Users\....\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266/Print.h line 60
0x40208c90: axTLS::WiFiClientSecure::available() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi\src/include/SSLContext.h line 273
0x4020dac4: Print::print(char const*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\Print.cpp line 122
0x40207396: FirebaseHTTPClient::http_sendHeader(char const*) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266HTTPClient.cpp line 58
0x402073c6: FirebaseHTTPClient::http_connect() at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266HTTPClient.cpp line 76
0x40207421: FirebaseHTTPClient::http_sendRequest(char const*, char const*) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266HTTPClient.cpp line 65
0x40218b49: __itoa at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/stdlib/itoa.c line 59
0x4020354d: FirebaseESP8266::sendFirebaseRequest(FirebaseData&, char const*, unsigned char, unsigned char, char const*, char const*, unsigned int) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 3545
0x40204cb9: FirebaseESP8266::firebaseConnect(FirebaseData&, std::string const&, unsigned char, unsigned char, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 1480
0x4022c45b: basic_read at ssl/tls1.c line 1374
0x4010020c: delayMicroseconds(unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring.cpp line 208
0x40100234: __digitalWrite(uint8_t, uint8_t) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring_digital.cpp line 85
0x4010020c: delayMicroseconds(unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring.cpp line 208
0x401000de: zcd() at C:\Users\...\Documents\Arduino\esp_home_control/esp_home_control.ino line 144
0x402077ac: ESP8266WiFiSTAClass::status() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp line 613
0x40205364: FirebaseESP8266::firebaseConnect(FirebaseData&, std::string const&, unsigned char, unsigned char, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 1718
0x40206b48: FirebaseESP8266::sendRequest(FirebaseData&, unsigned char, std::string const&, unsigned char, unsigned char, std::string const&, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 1828
0x40207075: FirebaseESP8266::buildRequest(FirebaseData&, unsigned char, unsigned char, std::string const&, char const*, bool, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 199
0x4020da69: Print::write(char const*) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266/Print.h line 60
0x4022031e: operator new(unsigned int) at ../../../../../dl/gcc-xtensa/libstdc++-v3/libsupc++/new_op.cc line 52
0x402071fd: FirebaseESP8266::setBool(FirebaseData&, std::string const&, bool, bool, std::string const&, std::string const&) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 728
0x40220c22: std::basic_string  , std::allocator  >::basic_string(char const*, std::allocator  const&) at /workdir/arena/gcc/xtensa-lx106-elf/libstdc++-v3/include/bits/basic_string.tcc line 218
0x401001a4: millis() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_wiring.cpp line 186
0x40207273: FirebaseESP8266::setBool(FirebaseData&, String const&, bool) at C:\Users\...\Documents\Arduino\libraries\Firebase-ESP8266-master\src\FirebaseESP8266.cpp line 688
0x4020e162: String::reserve(unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\WString.cpp line 148
0x4020e1c0: String::copy(char const*, unsigned int) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\WString.cpp line 211
0x4020e35c: String::operator=(String const&) at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\WString.cpp line 259
0x40201429: loop() at C:\Users\...\Documents\Arduino\esp_home_control/esp_home_control.ino line 85
0x4020e808: loop_wrapper() at C:\Users\...\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_main.cpp line 125

```

###Code
Same as above

**Comment by devyte** [comment]
Several comments from that last dump:
- I get the impression you're facing oom. Check free heap and max free block size at different places in your code
- We can't debug firebase. If the crash is in there, and I think it is, you'll have to discuss with the lib author. Try reducing your code to not use firebase and see if the issue is still there. 
- the dump shows use of axtls. That was deprecated some time ago, then the default was changed to bssl. In the (near) future it will be dropped altogether, so firebase should update to ise bssl sooner rather than later.
BTW, axtls doesn't behave well when faced with oom. 
- why do you have a global dynamic json buffer? I haven't been keeping up with that lib's most recent development, but at least thw last version I used did not allow reuse of a buffer, because mem would not be freed until destruction. I seem to remember that a reset would be added, if that happened you need to use it. I mention this, because you may have a mem leak there. 
- Try with 160MHz cpu. Use of ssl is cpu intensive.

**Comment by mobizt** [comment]
Nested interrupt causes heap corruption by stack growth due to the poster uses delay in his ISR.

**Comment by devyte** [comment]
Ah jeez I completely missed that, thanks @mobizt.
@arushgupta2007 you can't delay() in an ISR.

**Comment by arushgupta2007** [comment]
🎉 It worked!! 🎉

**Comment by arushgupta2007** [comment]
Thanks @mobizt  and @devyte  for your time and support!

**Comment by doublejosh** [comment]
Apparently also... `delayMicroseconds()` *does _not_* satisfy the watchdog, but `delay()` does!
